site_name: LPS Article
nav:
  - Introduction: README.md
  - Processing data:
    - Cross-Validation Framework: processing_data/cross_validation.md
    - Variant Filtering: processing_data/variant_filtering.md
    - Data Simulation: processing_data/data_simulation.md
  - Imputation:
    - Low-pass imputation: imputation/lps_imputation.md
    - Pseudo-array imputation: imputation/array_imputation.md
  - Evaluation:
    - Restructure imputed data: evaluation/restructure_imputed_data.md
    - LPS performance: 
      - LPS evaluation: evaluation/lps_performance.md
      - Visualization: evaluation/lps_visualization.md
    - PRS performance: 
      - PRS processing: evaluation/prs_processing.md
      - PRS evaluation: evaluation/prs_performace.md
      - Visualization: evaluation/prs_visualization.md
  - Available data: available_data.md
  - About: about.md
repo_name: KTest-VN/lps_paper
repo_url: https://github.com/KTest-VN/lps_paper
theme: 
  name: material
  color_mode: dark
  user_color_mode_toggle: false
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.footnote.tooltips
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.footer
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - abbr
  - attr_list
  - footnotes
  - pymdownx.blocks.caption
  - neoteroi.spantable
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra_css:
  - assets/stylesheets/extra.css
  - assets/css/neoteroi-mkdocs.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - mkdocs-jupyter:
      execute: false
  - bibtex:
      bib_file: "docs/assets/refs.bib"
      enable_inline_citations: false
  - glightbox