site_name: LPS Article
nav:
  - Introduction: README.md
  - Processing data:
    - Variant Filtering: processing_data/variant_filtering.md
    - Data Simulation: processing_data/data_simulation.md
    - Cross-Validation Framework: processing_data/cross_validation.md
  - Imputation:
    - Low-pass imputation: imputation/lps_imputation.md
    - Pseudo-array imputation: imputation/array_imputation.md
  - Evaluation:
    - Merge imputed data: evaluation/merge_imputed_data.md
    - LPS performance: evaluation/lps_performance.md
    - PRS performance: evaluation/prs_performace.md
  - Available data: available_data.md
  - About: about.md
repo_name: KTest-VN/lps_paper
repo_url: https://github.com/KTest-VN/lps_paper
theme: 
  name: material
  color_mode: dark
  user_color_mode_toggle: false
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.footnote.tooltips
    - navigation.instant
    - navigation.instant.prefetch
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - abbr
  - attr_list
  - footnotes
  - pymdownx.blocks.caption
  - neoteroi.spantable

extra_css:
  - assets/stylesheets/extra.css
  - assets/css/neoteroi-mkdocs.css

plugins:
  - mkdocs-jupyter:
      execute: false
  - bibtex:
      bib_file: "docs/assets/refs.bib"
      enable_inline_citations: false